### ISSUE TITLE
Task colors are now available

### ISSUE THREAD

**Issue by oliviermaridat** [xavividal/kanboard-plugin-relationgraph#4]
Hi @xavividal!

Thanks for the work on this plugin, this is really great!
For your information, task colours are now available when retrieving task links (see commit  https://github.com/fguillot/kanboard/commit/e09c565fdfea9a72b7d4e69717e022f84831eb20). So normally, you should now be able to colourise the graph...

(I may provide a PR if I found some time to do it)

**Comment by xavividal** [comment]
Yes, task colours are available, but the initial purpose of this graph is show which tasks are closed (red) and which ones are still pending/in progress (green).

I can customize the code and offer the two presentation behaviours: green/red or task colors. Or maybe try to mix the two informations and show everything.

Ok, I'll do some research and soon I'll publish an enhancement.
