### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by Jluisito** [xavividal/kanboard-plugin-relationgraph#7]
Hi Xavi,
I tried to install the plugin, apparently correctly, but when I click at the "Relation graph" link, in the task screen, I got a HTTP 500 Error. 
Can you help me?

Thanks!

**Comment by xavividal** [comment]
Update to the last version. There was some code non updated to the last version of Kanboard.

**Comment by Jluisito** [comment]
Now it works! 
Great job Xavi!
