### ISSUE TITLE
Zip archive should be extracted into a "Relationgraph" folder

### ISSUE THREAD

**Issue by fguillot** [xavividal/kanboard-plugin-relationgraph#8]
I merged your PR to publish your plugin on Kanboard's website but there is a small problem with the archive.

Extracting the zip file should create a folder "Relationgraph" instead of the name of your repo, in this way people can install the plugin in one click from the user interface of Kanboard.

**Comment by xavividal** [comment]
Thanks!

Which is the way to change the folder destination name? because we're using the ZIP files autogenerated by github for each release made by our tags.

**Comment by xavividal** [comment]
Ok, now I see, I can publish a own generated zip file and update data/plugins.php to point to this file.
